root: true
env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - prettier/react
rules:
  '@typescript-eslint/camelcase': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-var-requires': 'off'
  react/prop-types: 'off'
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  import/prefer-default-export: 'off'
  import/extensions: 'off'
  import/no-unresolved: 'off'
  import/no-extraneous-dependencies: 'off'
